globus/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('work_schedule/', views.AboutTechView.as_view(), name='work_schedule'),
]

globus/afisha/urls.py
from django.urls import path

from . import views

urlpatterns = [
     path('', views.index, name='index'),
     path('show_end/', views.show_end, name='show_end'),
     path('add_cinema/', views.add_cinema, name='add_cinema'),
     path('add_show_time/', views.add_show_time, name='add_show_time'),
     path('<int:id_cinema>/edit/', views.edit_cinema, name='edit_cinema'),
     path('<int:id_cinema>/<int:id_session>/edit/', views.edit_session,
          name='edit_session'),
     path('<int:id_cinema>/<int:id_session>/confrim_delete/',
          views.confrim_delete_session, name='confrim_delete_session'),
     path('<int:id_cinema>/<int:id_session>/delete/', views.delete_session,
          name='delete_session'),
]

globus/globus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import handler404, handler500
from django.urls import include, path

urlpatterns = [
    path('', include('afisha.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls')),
]

handler404 = 'afisha.views.page_not_found'  # noqa
handler500 = 'afisha.views.server_error'  # noqa

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

globus/afisha/models.py
from django.utils import timezone
from django.db import models


# TODO добавить постер к фильму
class Cinema(models.Model):
    title = models.CharField(max_length=50, null=False, verbose_name='Название ленты',)
    genre = models.CharField(max_length=50, verbose_name='Жанр ленты')
    duration = models.CharField(max_length=50, verbose_name='Длительность ленты')
    trailer = models.TextField(verbose_name='Вставка трейлера <iframe>',)
    description = models.TextField(verbose_name='Описание ленты',)
    mpaa = models.CharField(max_length=10, verbose_name='Возрастные ограничения',)
    source = models.CharField(max_length=200, verbose_name='Ссылка на источник')
    on_screen = models.BooleanField(verbose_name='В прокате')

    class Meta:
        ordering = ['title']
        verbose_name = 'Лента'
        verbose_name_plural = 'Ленты'

    def __str__(self):
        return self.title


class ShowTime(models.Model):
    datetime = models.DateTimeField(verbose_name='Дата показа',)
    price = models.PositiveIntegerField(verbose_name='Цена билета',)
    format = models.CharField(max_length=10, verbose_name='Формат ленты',)
    cinema = models.ForeignKey(Cinema, on_delete=models.CASCADE, verbose_name='Лента', related_name='show_time')

    class Meta:
        ordering = ['datetime']
        verbose_name = 'Время показа'
        verbose_name_plural = 'Время показа'

    def recentle_show(self):
        return self.datetime >= timezone.now()

globus/afisha/forms.py
from django import forms

from .models import Cinema, ShowTime


class CinemaForm(forms.ModelForm):
    class Meta:
        model = Cinema
        fields = '__all__'


class ShowTimeForm(forms.ModelForm):
    class Meta:
        model = ShowTime
        fields = '__all__'

globus/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/work_schedule.html'

globus/afisha/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page


from .models import Cinema, ShowTime
from .forms import CinemaForm, ShowTimeForm

paginator_pages = 10


# @cache_page(20)
def index(request):
    films = Cinema.objects.filter(on_screen=True).prefetch_related('show_time')
    paginator = Paginator(films, paginator_pages)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html', {'page': page})


# @cache_page(20)
def show_end(request):
    films = Cinema.objects.filter(on_screen=False).prefetch_related('show_time')
    paginator = Paginator(films, paginator_pages)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'show_end.html', {'page': page})


@login_required
def add_cinema(request):
    form = CinemaForm(request.POST or None)
    if form.is_valid():
        cinema = form.save(commit=False)
        cinema.save()
        return redirect('index')
    context = {
        'header': 'Добавить ленту',
        'form': form
    }
    return render(request, 'new_item.html', context)


@login_required
def edit_cinema(request, id_cinema):
    cinema = get_object_or_404(Cinema, id=id_cinema)
    form = CinemaForm(request.POST or None, instance=cinema)
    if form.is_valid():
        cinema = form.save(commit=False)
        cinema.save()
        return redirect('index')
    context = {
        'header': 'Редактирование ленты',
        'form': form
    }
    return render(request, 'new_item.html', context)


@login_required
def add_show_time(request):
    form = ShowTimeForm(request.POST or None)
    if form.is_valid():
        cinema = form.save(commit=False)
        cinema.save()
        return redirect('index')
    context = {
        'header': 'Добавить сеанс',
        'form': form
    }
    return render(request, 'new_item.html', context)


@login_required
def edit_session(request, id_cinema, id_session):
    session = get_object_or_404(ShowTime, id=id_session, cinema=id_cinema)
    form = ShowTimeForm(request.POST or None, instance=session)
    if form.is_valid():
        session = form.save(commit=False)
        session.save()
        return redirect('index')
    context = {
        'header': 'Редактирование сеанса',
        'form': form
    }
    return render(request, 'new_item.html', context)


@login_required
def confrim_delete_session(request, id_cinema, id_session):
    film = get_object_or_404(Cinema, id=id_cinema)
    session = get_object_or_404(ShowTime, id=id_session, cinema=id_cinema)
    return render(request, 'session.html', {'session': session, 'film': film})


@login_required
def delete_session(request, id_cinema, id_session):
    session = get_object_or_404(ShowTime, id=id_session, cinema=id_cinema)
    session.delete()
    return redirect('index')


def page_not_found(request, exception):
    return render(request, 'misc/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'misc/500.html', status=500)

globus/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load static %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-9 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3 text-center">
                  Об авторе проекта
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted text-center">
                  <p>Всем привет! Меня зовут Герман Артуров, я изучаю язык программирования Python и фреймворк Django.</p>
                    <p>Сайт создан в учебных целях и прямого отношения к кинотеатру "Глобус" не имеет.</p>
                    <p>На сайте можно посмотреть афишу, узнать расписание сеансов и стоимость билетов.</p>
                    <p>Расписание из <a href="https://www.instagram.com/kino_globus/" target="_blank"></a>инстаграма</a> кинотеатра.</p>
                    <p>Предложения по улучшению сайта можно отправить мне в Телеграм или VK.</p>
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-3">
        <div class="card">
        <div class="card-body text-left">
          <div class="text-left">
            <h3>Мои контакты</h3>
            <p><a href="https://github.com/ecmek" target="_blank"><img class="icon" src='{% static "/media/github_icon.png" %}'
                alt='GitHub'></a> Мой GitHub</p>
            <p><a href="https://vk.com/ecmek" target="_blank"><img class="icon" src='{% static "/media/vk_icon.png" %}'
                alt='VK'></a> Мой VK</p>
            <p><a href="https://www.instagram.com/germon4ik_/" target="_blank"><img class="icon" src='{% static "/media/instagram_icon.png" %}'
                alt='instagram'></a> Мой instagram</p>
            <p><a href="https://telegram.me/Ecmek" target="_blank"><img class="icon" src='{% static "/media/telegram_icon.png" %}'
                alt='Telegram'></a> Мой Telegram</p>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

globus/templates/about/work_schedule.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load static %}
  <main role="main" class="container">
    <div class="row justify-content-center">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-6 mb-3 mt-1 align-self-center">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3 text-center">
                  Режим работы
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted text-center">
                  <h3>Рабочие дни</h3>
                  с 09:00 до 21:00
                  <p>Вт, Ср, Чт, Пт, Сб, Вс</p>
                  <h3>Выходной день</h3>
                  <p>Понедельник</p>
                  <h3>Заказ билетов и бронь</h3>
                    +7 986-989-40-45
                  <h3>Адрес кинотеатра</h3>
                    <p>Саратовская обл., г. Красноармейск, ул. 1 Мая д.61</p>
                <h3>Расписание так же тут</h3>
                  <p><a href="https://www.instagram.com/kino_globus/" target="_blank"><img class="icon" src='{% static "/media/instagram_icon.png" %}'
                        alt='instagram'></a> instagram "Глобус"</p>
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
  </main>
{% endblock %}

globus/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="shortcut icon" href="#">
    <style>
    body {
        background-image: linear-gradient(to right, #74ebd5 0%, #9face6 100%);
    }
    </style>
    <!-- Yandex.Metrika counter -->
    <!-- <script type="text/javascript" >
        (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
    
        ym(81941428, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/81941428" style="position:absolute; left:-9999px;" alt="" /></div></noscript> -->
    <!-- /Yandex.Metrika counter -->
    <!-- /Google.Adsense -->
    <script data-ad-client="ca-pub-1149826189042698" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- /Google.Adsense -->
    <title>{% block title %}Киноафиша кинотеатра "Глобус"{% endblock %}</title>
</head>
<body>
    {% include 'includes/nav.html' %}
    <div class="container">
        <h1 class="text-center">{% block header %}{% endblock %}</h1>
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

globus/templates/includes/film_item.html
  <h3 class="card-header bg-dark text-white text-center">{{ film.title }}
    {% if user.is_staff %}
    <a class="btn btn-sm btn-primary" href="{% url 'edit_cinema' film.id %}" role="button">Редактировать</a>
    {% endif %}
  </h3>

  <div class="row">
    <div class="col-lg-4 col-md-12 col-sm-12 mx-2 mt-2">
      {{ film.trailer|safe }}
    </div>
    <div class="card col-lg-2 col-md-12 col-sm-12 mx-2 mt-2">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Возраст: {{ film.mpaa }}</li>
        <li class="list-group-item">Длительность: {{ film.duration }}</li>
        <li class="list-group-item">Жанр: {{ film.genre }}</li>
      </ul>
    </div>
    <div class="card col-lg-5 col-md-12 col-sm-12 mx-2 mt-2">
      <div class="card-header bg-dark text-white text-center row">Краткий обзор</div>
      <div class="card-body row">
        {{ film.description }}
      </div>
        <small class="card-footer text-muted row"><a href='{{ film.source }}'>Источник</a></small>
    </div>
  </div>

globus/templates/includes/menu.html
<div class="row mx-auto">
    <ul class="nav nav-tabs mx-auto">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
          На экранах
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if show_end %}active{% endif %}" href="{% url 'show_end' %}">
          Показ закончен
        </a>
      </li>
    </ul>
</div>

globus/templates/includes/nav.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Киноафиша <span style="color:#74ebd5">"Глобус"</a></span>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'about:work_schedule' %}">О кинотеатре</a>
            </li>    
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'about:author' %}">Об авторе</a>
            </li>    
        {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'add_cinema'%}">Добавить кино</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'add_show_time' %}">Добавить показ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'logout' %}" tabindex="-1" aria-disabled="true">Выйти</a>
          </li>
        {% endif %}
        </ul>
      </div>

    </div>
  </nav>

globus/templates/includes/paginator.html
{% if page.has_other_pages %}
<nav class="nav justify-content-center">
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

globus/templates/includes/session_item.html
<div class="card col-lg-2 col-md-5 col-sm-3 mx-2 mt-2 mb-2 text-center">
    <ul class="list-group list-group-flush">
      <li class="list-group-item bg-light row">{{ session.datetime|date:"d.m в H:i"}}</li>
      <li class="list-group-item row">Формат: {{ session.format }}</li>
      <li class="list-group-item row">Цена: {{ session.price }}р</li>
      {% if user.is_staff %}
      <div class="d-flex justify-content-between align-items-center row">
      <a class="btn btn-sm btn-primary" href="{% url 'edit_session' film.id session.id %}" role="button">Редактировать</a>
      <a class="btn btn-sm btn-danger" href="{% url 'confrim_delete_session' film.id session.id %}" role="button">Удалить</a>
      </div>
      {% endif %}
    </ul>
</div>

globus/templates/index.html
{% extends "base.html" %}
{% block title %}Киноафиша кинотеатра "Глобус"{% endblock %}
{% block header %}Киноафиша кинотеатра "Глобус"{% endblock %}
{% block content %}
{% include "includes/menu.html" with index=True %}

  {% for film in page %}
  <div class="card mb-2 shadow-sm">
    {% include 'includes/film_item.html' %}
      <div class="container mb-2 mt-2">
        <div class="card shadow-sm">
          <div class="card-header">Cеансы</div>
            <div class="row mx-1">
              {% for session in film.show_time.all %}
              {% if session.recentle_show %}
                {% include 'includes/session_item.html' %}
              {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    {% include "includes/paginator.html" with items=page paginator=paginator %}
{% endblock %}

globus/templates/new_item.html
{% extends "base.html" %}
{% block title %}{{ header }}{% endblock %}
{% block header %}{% endblock %}
{% load form_control %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-10 p-5">
    <div class="card">
        <div class="card-header">{{ header }}</div>
        <div class="card-body">
            {% for error in form.errors.values %}
            <div class="alert alert-danger" role="alert">
                {{ error|escape }}
            </div>
            {% endfor %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                    <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                      <div class="col-md-6">
                      {{ field }}
                      {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                      {% endif %}
                      </div>                
                </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">              
                  <button type="submit" class="btn btn-primary">
                  Сохранить
                  </button>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>
{% endblock %}

globus/templates/session.html
{% extends "base.html" %}
{% block content %}
<div class="card col-lg-2 col-md-5 col-sm-3 mx-2 mt-2 mb-2 text-center">
    <ul class="list-group list-group-flush">
      <li class="list-group-item bg-light row">{{ session.datetime|date:"d.m в H:i"}}</li>
      <li class="list-group-item row">Формат: {{ session.format }}</li>
      <li class="list-group-item row">Цена: {{ session.price }}р</li>
      {% if user.is_staff %}
      <div class="d-flex justify-content-between align-items-center row">
      <a class="btn btn-sm btn-primary" href="{% url 'edit_session' film.id session.id %}" role="button">Редактировать</a>
      <a class="btn btn-sm btn-danger" href="{% url 'delete_session' film.id session.id %}" role="button">Удалить</a>
      </div>
      {% endif %}
    </ul>
</div>
{% endblock %}

globus/templates/show_end.html
{% extends "base.html" %}
{% block title %}Киноафиша кинотеатра "Глобус"{% endblock %}
{% block header %}Киноафиша кинотеатра "Глобус"{% endblock %}
{% block content %}

  {% include "includes/menu.html" with show_end=True %}

  {% for film in page %}
  <div class="card mb-2 shadow-sm">
    {% include 'includes/film_item.html' %}
  </div>
  {% endfor %}

  {% include "includes/paginator.html" with items=page paginator=paginator %}

{% endblock %}